# Generated by Django 4.2.14 on 2024-07-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_transaction_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
    ]
